server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shali12359/microservices-config-store.git
          search-paths:
            - 'service-config/*service'
