server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shali12359/spring-cloud-config-store.git
          search-paths:
            - '*service'
